[package]
name = "enum-ordinalize"
version = "2.5.2"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/enum-ordinalize"
homepage = "https://magiclen.org/enum-ordinalize"
keywords = ["enum", "ordinal", "ordinalize", "number"]
categories = ["data-structures"]
description= "This crates provides `create_ordinalized_enum` macro to let enums can not only get its variants' ordinal but also be constructed from an ordinal."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/enum-ordinalize"
branch = "master"

[dependencies]

[features]
nightly-test = []